import 'package:get/get.dart';

class BrandController extends GetxController {

  var brandList = <String>[
    "Nike",
    "Adidas",
    "Puma",
    "Reebok",
    "Under Armour",
    "New Balance",
    "Asics",
    "Fila",
    "Converse",
    "Vans",
    "Elite Edge",
    "Pure Glow",
    "Urban Vibe",
    "Swift Nest",
    "Nexa Trend",
    "Aura Rise",
    "Vivid Wave",
    "Lush Bloom",
    "Prime Pulse",
    "Quantum Vox",
    "Epic Aura",
    "Nova Niche",
    "Trend Horizon",
    "Glow Sphere",
    "Spark Zen",
    "Velvet Peak",
    "Bold Vista",
    "Zentro Lux",
    "RadianceX",
    "Luxe Vista",
    "Infinite Glow",
    "Verve Line",
    "Glitz Core",
    "Lumin Quest",
    "Cosmo Nest",
    "Celesti Wave",
    "Noble Nest",
    "Vero Sync",
    "Eco Vortex",
    "Peak Glow",
    "Magna Lux",
    "Zest Flare",
    "Enchantiq",
    "Opulent Vibe",
    "Fusion Aura",
    "Brio Nex",
    "Aether Glow",
    "Vision Echo",
    "Vital Edge",
    "Evo Sage",
    "Neon Flair",
    "Aura Vance",
    "Lush Sphere",
    "Strato Nex",
    "Opal Horizon",
    "Syner Glow",
    "Mirage Nest",
    "Halo Trend",
    "Vertex Glow",
    "Titan Verve",
    "Pulse Luxe",
    "Eclipse Edge",
    "OmniVibe",
    "Quantum Trend",
    "Zephyr Nest",
    "Prisma Vox",
    "Virtu Glow",
    "Elevate Zen",
    "Enigma Luxe",
    "Radiant Echo",
    "Stellar Hue",
    "Astra Glow",
    "Momentum Vibe",
    "Glitz Nexus",
    "Glow Opus",
    "Celeste Edge",
    "Lustre Trend",
    "Panache Lux",
    "Urban Aura",
    "Neo Brilliance",
    "Optima Zen",
    "Glow Vertex",
    "Gleam Nest",
    "Zenith Aura",
    "Bliss Quotient",
    "Luxe Fusion",
    "Omni Glow",
    "Zest Horizon",
    "Trend Pulse",
    "Lush Echo",
    "Hyper Vibe",
    "Magnetique",
    "Brilliance Nexus",
    "Flair Nest",
    "Natura Luxe",
    "Euphoria Edge",
    "ExuberanceX",
    "Infinity Hue",
    "Nova Zen",
    "Neon Aura",
    "Halo Sphere",
    "Enchanted Edge",
    "Ever Lush",
    "Prism Aura",
    "Glow Horizon",
    "Vortex Vibe",
    "Radiance Nest",
    "Elite Zen",
  ].obs;

  var searchQuery = ''.obs;

  List<String> get filteredBrands => brandList
      .where((brand) =>
          brand.toLowerCase().contains(searchQuery.value.toLowerCase()))
      .toList();

  void updateSearchQuery(String query) {
    searchQuery.value = query;
  }
}
